# Documentation

No matter how much of a framework's API we cover here,
there will always be functions, classes, and arguments
we never reach, and the libraries keep changing under us.
So rather than try to memorize the API,
the durable skill is getting good at *looking things up*:
finding what exists, reading how it works,
and confirming that it does what you think.
This short section lays out a small, repeatable loop for exactly that,
using tools built into Python and your notebook.

The official documentation is always the source of truth;
bookmark the reference and tutorial pages for the framework you use.

For TensorFlow these are the
[API reference](https://www.tensorflow.org/api_docs) and the
[tutorials](https://www.tensorflow.org/tutorials).

For most day-to-day questions, though, you do not need to leave your
notebook. Four moves, repeated until the call behaves, cover almost
everything.

![Four moves, repeated until the call does what you want: **discover** the names that exist, **inspect** a candidate's signature, **read** the docs or source when you need the *why*, and **verify** with a quick run.](https://raw.githubusercontent.com/smolix/d2l-neu/notebooks/img/lookup-api-discovery-loop.svg)

The examples below start from the standard import:

In [1]:
import tensorflow as tf

## Discovering What Exists: `dir`

When you know roughly *where* a tool should live but not what it is called,
the `dir` function lists everything defined in a module.
For instance, to see what is on offer for random sampling
(we print the first twenty names):

In [2]:
print([name for name in dir(tf.random) if not name.startswith('_')][:20])

['Algorithm', 'Generator', 'all_candidate_sampler', 'categorical', 'create_rng_state', 'experimental', 'fixed_unigram_candidate_sampler', 'fold_in', 'gamma', 'get_global_generator', 'learned_unigram_candidate_sampler', 'log_uniform_candidate_sampler', 'normal', 'poisson', 'set_global_generator', 'set_seed', 'shuffle', 'split', 'stateless_binomial', 'stateless_categorical']


We can usually ignore names that begin and end with `__`
(Python's special objects) or that start with a single `_`
(internal helpers). The remaining names already hint
at what the module offers.

Here we can spot samplers such as `gamma`, `normal`, and `poisson`,
next to utilities like `Generator` and `set_seed` that manage the
random state.

In a notebook you can get the same list interactively, filtered as you
type, by writing the module name followed by a dot and pressing `Tab`;
this is usually the fastest way to turn up a name.

## Reading the Signature: `help`, `?`, and `??`

Once you have a name, `help` prints its docstring:
the arguments it takes, their defaults, what it returns,
and often a short example. Let us look up the `ones` function,
which we have used to build tensors:

In [3]:
help(tf.ones)

Help on function ones in module tensorflow.python.ops.array_ops:

ones(shape, dtype=tf.float32, name=None, layout=None)
    Creates a tensor with all elements set to one (1).

    See also `tf.ones_like`, `tf.zeros`, `tf.fill`, `tf.eye`.

    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to one.

    >>> tf.ones([3, 4], tf.int32)
    <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
    array([[1, 1, 1, 1],
           [1, 1, 1, 1],
           [1, 1, 1, 1]], dtype=int32)>

    Args:
      shape: A `list` of integers, a `tuple` of integers, or a 1-D `Tensor` of
        type `int32`.
      dtype: Optional DType of an element in the resulting `Tensor`. Default is
        `tf.float32`.
      name: Optional string. A name for the operation.
      layout: Optional, `tf.experimental.dtensor.Layout`. If provided, the result
        is a [DTensor](https://www.tensorflow.org/guide/dtensor_overview) with the
        provided layout.

    Returns:
      A `

The docstring tells us that `ones` creates a new tensor of the requested
shape with every element set to 1.
In a Jupyter notebook, two shortcuts make this quicker still:
`ones?` opens the same docstring in a side pane,
and `ones??` additionally displays the function's *source code*.
The source is the final word when a docstring is terse or ambiguous,
and reading it is one of the better ways to pick up idioms
from high-quality libraries.

## Verifying With a Quick Run

Docstrings can be terse, and they occasionally drift out of date.
The fastest way to be certain is to run a tiny example
and look at the result:

In [4]:
tf.ones(4)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

The shape and values are exactly what the docstring promised.
Making this `discover → inspect → read → verify` loop a habit
will carry you through the unfamiliar corners of any library,
long after the specific functions in this book have changed.

Coding assistants are often the quickest route to a first answer:
ask "how do I sample from a normal distribution in this framework?"
and you will usually get a function and a working call in seconds.
Treat the suggestion the way you would a knowledgeable colleague's tip:
a good starting point that still goes through the loop above.
Glance at the signature with `help` or `?`, run a small example,
and rely on the suggestion once it survives both.

## Exercises

1. Use `dir` on your framework's random-number module to find the routine
   that samples from a *uniform* distribution. Read its signature with `help`
   (or `?`), then call it to draw a $3 \times 3$ tensor and confirm the values
   lie in $[0, 1)$.
1. You want to reduce a tensor along a single axis but cannot remember the
   keyword. Look up your framework's `sum` (or `reduce_sum`) with `help`,
   identify the argument that selects the axis, and verify on a $2 \times 3$
   tensor that summing over each axis gives the shape you predicted.
1. Ask a coding assistant "how do I concatenate two tensors along a new axis
   in my framework?" Then run its answer through the
   discover&nbsp;&rarr;&nbsp;inspect&nbsp;&rarr;&nbsp;read&nbsp;&rarr;&nbsp;verify
   loop: does the suggested function exist (`dir`), does its signature match
   the claim (`help`/`?`), and does a tiny example do what you expect?

[Discussions](https://d2l.discourse.group/t/199)