# Documentation

A framework API contains more functions, classes, and arguments than any
single text can cover, and it changes across releases. Effective use therefore
depends on being able to find an operation, inspect its interface, read its
documentation, and verify its behavior with a small example. This section
demonstrates that procedure using Python and notebook tools.

The official reference and tutorial pages document the supported interface for
each framework.

For TensorFlow these are the
[API reference](https://www.tensorflow.org/api_docs) and the
[tutorials](https://www.tensorflow.org/tutorials).

Many routine questions can be answered without leaving the notebook. The
procedure has four steps: discover, inspect, read, and verify.

![A four-step procedure for using an unfamiliar API: discover available names, inspect a candidate's signature, read its documentation or source, and verify its behavior with a small example.](https://raw.githubusercontent.com/smolix/d2l-neu/notebooks/img/lookup-api-discovery-loop.svg)

The examples below start from the standard import:

In [1]:
import tensorflow as tf
from pprint import pprint

## Discovering What Exists: `dir`

When you know roughly *where* a tool should live but not what it is called,
the `dir` function lists the names defined in a module.
For instance, to inspect the available random-sampling tools
(we print the first twenty names):

In [2]:
pprint([name for name in dir(tf.random)
        if not name.startswith('_')][:20], compact=True)

['Algorithm', 'Generator', 'all_candidate_sampler', 'categorical',
 'create_rng_state', 'experimental', 'fixed_unigram_candidate_sampler',
 'fold_in', 'gamma', 'get_global_generator',
 'learned_unigram_candidate_sampler', 'log_uniform_candidate_sampler', 'normal',
 'poisson', 'set_global_generator', 'set_seed', 'shuffle', 'split',
 'stateless_binomial', 'stateless_categorical']


We can usually ignore names that begin and end with `__`
(Python's special objects) or that start with a single `_`
(internal helpers). The remaining names already hint
at what the module offers.

Here we can spot samplers such as `gamma`, `normal`, and `poisson`,
next to utilities like `Generator` and `set_seed` that manage the
random state.

In a notebook you can get the same list interactively, filtered as you
type, by writing the module name followed by a dot and pressing `Tab`;
this often locates a name quickly.

## Reading the Signature: `help`, `?`, and `??`

Once you have a name, `help` prints its docstring:
the arguments it takes, their defaults, what it returns,
and often a short example. Let us look up the `ones` function,
which we have used to build tensors:

In [3]:
help(tf.ones)

Help on function ones in module tensorflow.python.ops.array_ops:

ones(shape, dtype=tf.float32, name=None, layout=None)
    Creates a tensor with all elements set to one (1).

    See also `tf.ones_like`, `tf.zeros`, `tf.fill`, `tf.eye`.

    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to one.

    >>> tf.ones([3, 4], tf.int32)
    <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
    array([[1, 1, 1, 1],
           [1, 1, 1, 1],
           [1, 1, 1, 1]], dtype=int32)>

    Args:
      shape: A `list` of integers, a `tuple` of integers, or a 1-D `Tensor` of
        type `int32`.
      dtype: Optional DType of an element in the resulting `Tensor`. Default is
        `tf.float32`.
      name: Optional string. A name for the operation.
      layout: Optional, `tf.experimental.dtensor.Layout`. If provided, the result
        is a [DTensor](https://www.tensorflow.org/guide/dtensor_overview) with the
        provided layout.

    Returns:
      A `

The docstring tells us that `ones` creates a new tensor of the requested
shape with every element set to 1.
In a Jupyter notebook, two shortcuts make this quicker still:
`ones?` opens the same docstring in a side pane,
and `ones??` additionally displays the function's *source code*.
When a docstring is terse or ambiguous, the source can clarify the
implementation. Reading library source also reveals established usage idioms.

## Verifying With a Quick Run

Docstrings can be terse, and they occasionally drift out of date.
A small example can verify the behavior directly:

In [4]:
tf.ones(4)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

The result has the documented shape and values.
Making this `discover → inspect → read → verify` loop a habit
will carry you through the unfamiliar corners of any library,
long after the specific functions in this book have changed.

Coding assistants can propose an API call for a question such as “how do I
sample from a normal distribution in this framework?” Treat the result as an
unverified candidate that still goes through the loop above.
Glance at the signature with `help` or `?`, run a small example,
and accept the suggestion only once it survives both.

## Summary

For an unfamiliar operation, discover candidate names, inspect the signature,
read the relevant documentation, and verify the behavior with the smallest run
that exposes shapes, dtypes, and values. This procedure remains valid as library
APIs change and applies equally to suggestions from search or coding assistants.

## Exercises

1. Use `dir` on your framework's random-number module to find the routine
   that samples from a *uniform* distribution. Read its signature with `help`
   (or `?`), then call it to draw a $3 \times 3$ tensor and confirm the values
   lie in $[0, 1)$.
1. You want to reduce a tensor along a single axis but cannot remember the
   keyword. Look up your framework's `sum` (or `reduce_sum`) with `help`,
   identify the argument that selects the axis, and verify on a $2 \times 3$
   tensor that summing over each axis gives the shape you predicted.
1. Ask a coding assistant "how do I concatenate two tensors along a new axis
   in my framework?" Then run its answer through the
   discover&nbsp;&rarr;&nbsp;inspect&nbsp;&rarr;&nbsp;read&nbsp;&rarr;&nbsp;verify
   loop: does the suggested function exist (`dir`), does its signature match
   the claim (`help`/`?`), and does a tiny example do what you expect?

[Discussions](https://d2l.discourse.group/t/199)